services:
  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Frontend
      - "5000:5000" # Backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
      - DATABASE_URL=postgres://postgres:postgres@db:5432/app_db
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      # - FIREBASE_API_KEY=${FIREBASE_API_KEY}
      # - KEEP_THE_SCORE_API_KEY=${KEEP_THE_SCORE_API_KEY}
    volumes:
      - .:/root/codebytes
    depends_on:
      - db
      - elasticsearch
      - pgadmin
    working_dir: /root

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

volumes:
  pgdata:
  pgadmin_data:
