services:
  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Frontend
      - "5000:5000" # Backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
      - DATABASE_URL=postgres://postgres:postgres@db:5432/app_db
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
      - FIREBASE_API_KEY=${FIREBASE_API_KEY}
      - FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
      - JUDGE0_API_URL=http://judge0-api:9000 # Add this for Judge0
    volumes:
      - .:/root/codebytes
    depends_on:
      - db
      - elasticsearch
      - pgadmin
      # - firebase
      - judge0-api
    working_dir: /root

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.3
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"

  # firebase:
  #   image: firebase/firebase-tools:latest
  #   ports:
  #     - "5001:5000"
  #     - "9199:9199"

  judge0-api:
    image: judge0/judge0:latest
    ports:
      - "9000:9000"
    environment:
      - JUDGE0_API_JUDGE0_RUNTIME_URL=http://judge0-runtime:8080
      - JUDGE0_API_JUDGE0_RUNTIME_TOKEN=your-secret-token
    depends_on:
      - judge0-runtime

  judge0-runtime:
    image: judge0/judge0:latest
    environment:
      - JUDGE0_RUNTIME_TOKEN=your-secret-token
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  pgdata:
  pgadmin_data:
