# Dockerfiles/Dockerfile.backend
FROM node:18-alpine

# Install Git
RUN apk add --no-cache git

WORKDIR /app

COPY backend/package*.json ./
RUN npm install

COPY backend/ ./

EXPOSE 5000
CMD ["node", "app/index.js"]

