# Dockerfiles/Dockerfile.frontend
FROM node:18-alpine

# Install Git
RUN apk add --no-cache git

WORKDIR /app

COPY frontend/package*.json ./
RUN npm install

COPY frontend/ ./

EXPOSE 3000
CMD ["npm", "run", "dev"]

